# Generated by Django 3.1.4 on 2020-12-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeword', models.BigIntegerField()),
                ('is_view', models.BooleanField()),
                ('view', models.CharField(max_length=255)),
            ],
        ),
    ]
