# Generated by Django 3.1.4 on 2020-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0002_auto_20201219_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='view',
            new_name='view_1',
        ),
        migrations.AddField(
            model_name='clue',
            name='view_2',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
