# Generated by Django 3.1.4 on 2020-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0003_auto_20201219_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='viewed_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='viewed_2',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
